### ISSUE TITLE
Error Code: Bloodstone

### ISSUE THREAD

**Issue by Pikl** [aytiel/PHTM-b0t#5]
Attempting to process logs gives me "Bloodstone" error message for every log.

I don't know Python at all, but it looks like it has no idea about the logs even existing so I'm assuming it's something to do with pathing issues.

The bot is currently stored in `D:\Downloads\DiscReportBot\`
My documents folder is also on D:\\, so the log file path is `D:\Documents\Guild Wars 2\addons\arcdps\arcdps.cbtlogs\`
Note that my OS, W10 is on C:\

I've tried giving the bot a direct path to the logs incase it cannot locate the documents folder, replacing line 77 in arcdps.py to `path = 'D:\Documents\Guild Wars 2\addons\arcdps\arcdps.cbtlogs\*'` but the result is the same.
I've tried storing the bot on C:\ and again, no difference.

Also, please consider using actual error messages with descriptions, these themed error "codes" are just getting in the way at best.

Thanks.

**Comment by aytiel** [comment]
Thanks for bringing this to my attention.

The issue has no relation to where the bot is stored or where your OS is installed. The problem is the particular code for that line assumes the path to always be `C:\Users\USER\Documents\Guild Wars 2\addons\arcdps\arcdps.cbtlogs\`, which is typically where most people's logs folder is located. I will have to try to figure out a better way for more accurate pathing. 

For the time being, replace line 77 in arcdps.py with `path = '{0}{1}/*'.format('D:/Documents/Guild Wars 2/addons/arcdps/arcdps.cbtlogs/', b)`. That should fix your issue. Let me know if that isn't the case.

As for the themed error codes, I appreciate the feedback, but the reason I decided to go with the error codes was so that I could distinguish the particular issue while still being layman-friendly. If more people express the same concerns that you did, I will consider being more descriptive, but for the time being, I still wish to use the error codes.
