### ISSUE TITLE
Better Pathing

### ISSUE THREAD

**Issue by aytiel** [aytiel/PHTM-b0t#6]
Implemented a better solution for users whose logs folders are not located in their user folders.

**Comment by Argurotoxus** [comment]
Hey! I see you closed this issue, but I'm having the same problem and I'm not sure what your better solution is. I've tried replacing line 79 with my file destination as such:

path = '{0}{1}/*'.format('E:/Documents/Guild Wars 2/addons/arcdps/arcdps.cbtlogs/', b)

But it's not working. I don't know Python at all, so I'm not quite sure where to go from here.

**Comment by Argurotoxus** [comment]
To clarify, I am getting the BLOODSTONE error. My logs are located in E:/Documents/Guild Wars 2/addons/arcdps/arcdps.cbtlogs/. 

EDIT: Nevermind. Changing the file path maybe worked, I just had to reboot the bot because I'm a moron.

It still doesn't seem to be uploading but I'm not getting an error. We'll see, I'll keep playing with it.
